### ISSUE TITLE
Download speedtest.png failed!

### ISSUE THREAD

**Issue by satgit62** [m4dhouse/Internet-Speedtest#1]
Thank you for your plugin, so far it has worked wonderfully and didn't cause any problems. At the moment, however, the message comes up when saving the results, “Download speedtest.png failed!” Since the whole thing is based on “speedtest-cli”, I tried to determine the speed test results via SSH/Telnet. This can be done with the command “speedtest-cli --share”. After entering and running the tests: Share results: http://www.speedtest.net/result/xxx6590995.png. When entering in browser, http://www.speedtest.net/result/xxx6590995.png. If you see the .png picture with the measurement result. What could be that is not working in plugin itself? Have they changed anything on the speedtest.net server, and does “speedtest.py” have to be adjusted?

Danke für dein Plugin, bis jetzt hat wunderbar funktioniert und keinerlei zicken gemacht. Zurzeit kommt aber die Meldung beim Ergebnisse Speichern, „Download speedtest.png fehlgeschlagen!“ Da das ganze auf „speedtest-cli“ basiert, habe versucht, über SSH/Telnet die Speedtestergebnisse zu ermitteln. Das geht mit der Befehl „speedtest-cli --share“. Nach Eingabe und Durchführung der Tests kommt: Share results: http://www.speedtest.net/result/xxx6590995.png. Beim Eingabe in Browser http://www.speedtest.net/result/xxx6590995.png. Sieht man das .png Bild mit dem Messergebnis. Was könnte sein, dass in Plugin selbst nicht funktioniert? Haben die was am speedtest.net Server was umgestellt, und muss die „speedtest.py“ angepasst werden?

**Comment by m4dhouse** [comment]
Hi, please install the new version 1.4.
The problem was on the user-agent, the request was refused with a 403 error.
