### ISSUE TITLE
https-fix!

### ISSUE THREAD

**Issue by Token2K** [m4dhouse/Internet-Speedtest#2]
https-workaround for plugin.py:
Line 8:
old: cmd = 'python ' + plugin_path + ' --no-pre-allocate --share'
new: cmd = 'python ' + plugin_path + ' --no-pre-allocate --share --secure'
Line 352:
old: self.cmd = 'python ' + plugin_path + ' --no-pre-allocate --server %s --share' % (self.server)
new: self.cmd = 'python ' + plugin_path + ' --no-pre-allocate --server %s --share --secure' % (self.server)
tested with py2!

**Comment by Token2K** [comment]
Unfortunately, that was only half the solution!
The selection of alternative servers still leads to an HTTP 403 error.

the change in Line 352 or also as an attempt in Line 288 is not purposeful - and can be reset!

**Comment by Token2K** [comment]
@NaseDC from the VU+ forum has found the correct syntax:

Line 28:
old: cmd = 'python ' + plugin_path + ' --no-pre-allocate --share'
new: cmd = 'python ' + plugin_path + ' --no-pre-allocate --share --secure'

Line 289:
old: myfavserv= subprocess.Popen(['python', '/usr/lib/enigma2/python/Plugins/Extensions/InternetSpeedTest/speedtest.py', '--list'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
			stdout,stderr = myfavserv.communicate()
new: myfavserv= subprocess.Popen(['python', '/usr/lib/enigma2/python/Plugins/Extensions/InternetSpeedTest/speedtest.py', '--list', '--secure'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
			stdout,stderr = myfavserv.communicate()

... he has declared it there as V1.5.1-VTi!
... and I tested it on a VU+Solo2 with Openpli 8.3 (py2) against!

**Comment by m4dhouse** [comment]
It works perfectly, thx
